### PR TITLE
List modifiers in describe command

### PR DESCRIPTION
**Pull request by maurelian**
This is a simple change to add a list of modifiers, when present, on a new line. 

If desired, we could add a flag to make this behavior optional.

Example:

Pool (Initializable, ReentrancyGuard)
    - [Pub] init #
       - modifiers: initializer
    - [Int] open #
    - [Int] commit #
    - [Pub] openNextDraw #
       - modifiers: onlyAdmin,unlessPaused
    - [Pub] rewardAndOpenNextDraw #
       - modifiers: onlyAdmin,unlessPaused
    - [Int] reward #
    - [Int] calculateFee
    - [Pub] depositSponsorship #
       - modifiers: nonReentrant,unlessPaused
    - [Pub] depositPool #
       - modifiers: requireOpenDraw,nonReentrant,unlessPaused

### CODE REVIEW

**Comment by GNSPS** [comment]
This diff looks super strange but I think I can see the changes regardless of what changes it claims you made.

I am going to do three changes, after you give your ok:
* indent the new "modifiers" line
* point the PR to `develop`
* squash the commits

**Comment by maurelian** [comment]
Whoa... no, something went wrong. The diff should be tiny.
Don't spend any time on this right now.

**Comment by maurelian** [comment]
Fixed it. Some stupid vscode setting was changing the indentation.

**Comment by GNSPS** [comment]
Thank you! 🙏

**Pull request merged**
